<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function product_suggested_views_handlers() {
    return array(
        'info' => array(
            'path' => drupal_get_path('module', 'product_suggested') . '/views',
        ),
        'handlers' => array(
            'views_handler_filter_product_suggested' => array(
                'parent' => 'views_handler_field',
            ),
        ),
    );
}

/**
 * Implementation of hook_views_data()
 */
function product_suggested_views_data() {
    $data = array();

    $data['term_node']['suggest'] = array(
        'title' => t('Products Suggested'),
        'help' => t('Contains the products suggested'),
        'filter' => array(
            'title' => t('Product Suggested'),
            'handler' => 'views_handler_filter_product_suggested',
            'numeric' => TRUE,
        ),
    );
  
    return $data;
}

