<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function product_related_views_handlers() {
    return array(
        'info' => array(
            'path' => drupal_get_path('module', 'product_related') . '/views',
        ),
        'handlers' => array(
            'views_handler_filter_product_related' => array(
                'parent' => 'views_handler_field',
            ),
        ),
    );
}

/**
 * Implementation of hook_views_data()
 */
function product_related_views_data() {
    $data = array();

    $data['term_node']['related'] = array(
        'title' => t('Products related'),
        'help' => t('Products related to the artist'),
        'filter' => array(
            'title' => t('Product related'),
            'handler' => 'views_handler_filter_product_related',
            'numeric' => TRUE,
        ),
    );
    
    return $data;
}

