<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function product_consulted_views_handlers() {
    return array(
        'info' => array(
            'path' => drupal_get_path('module', 'product_consulted') . '/views',
        ),
        'handlers' => array(
            'views_handler_filter_product_consulted' => array(
                'parent' => 'views_handler_field',
            ),
        ),
    );
}

/**
 * Implementation of hook_views_data()
 */
function product_consulted_views_data() {
    $data = array();

    $data['term_node']['consulted'] = array(
        'title' => t('Products consulted'),
        'help' => t('Users also consulted'),
        'filter' => array(
            'title' => t('Product consulted'),
            'handler' => 'views_handler_filter_product_consulted',
            'numeric' => TRUE,
        ),
    );

    return $data;
}

